/*
 * ecat_conf.h - EtherCAT Library Configuration
 *
 * Copyright (C) 1998-2026  by port GmbH  Halle(Saale)/Germany
 *
 *------------------------------------------------------------
 * This file was generated by the Industrial Communication Creator
 * with EtherCAT feature V7.6.0.202512051012
 * from project C:\Projects\ICCTest\RIOP-ECAT-APP-GLUE-V1.5.0\ecat_io.iccproj
 * on 2026/03/18 at 12:01:03.
 */

/**
 * \file ecat_conf.h
 * \author port GmbH
 *
 * This module contains the configuration
 * of the EtherCAT Library for the EtherCAT device.
 */



#ifndef ECAT_CONF_H
#define ECAT_CONF_H	1
#define EC_CONFIG_ICCTOOL_VERSION 0x00070600

/* active configuration : 0 */
#define EC_CONFIG_USE_TARGET_0 1


/*
 * General Settings
 */

#define EC_CONFIG_DYNAMIC_OD                     1
#define EC_CONFIG_NO_LOCAL_OD                    1
#define EC_CONFIG_BOOTSTRAP                 	1
#define EC_CONFIG_BOOTSTRAP_MBOXIN_ADR      	0x1000
#define EC_CONFIG_BOOTSTRAP_MBOXIN_SIZE     	0x400
#define EC_CONFIG_BOOTSTRAP_MBOXOUT_ADR     	0x1400
#define EC_CONFIG_BOOTSTRAP_MBOXOUT_SIZE    	0x400
#define EC_CONFIG_DC                        	1
#define EC_CONFIG_DYNAMIC_OD                	1
#define EC_CONFIG_DYN_CFG                   	1
#define EC_CONFIG_EMERGENCY                 	1
#define EC_CONFIG_EMERGENCY_QUEUESIZE       	8
#define EC_CONFIG_PDI_INTERRUPT             	1
#define EC_CONFIG_PDO_RAM_BUF_SIZE          	128
#define EC_CONFIG_REQUEST_TIMEOUT           	2000
#define EC_CONFIG_RESPONSE_TIMEOUT          	10000
#define EC_CONFIG_SDO_INFO                  	1
#define EC_CONFIG_SDO_SEG_BUF_LEN           	1024
#define EC_CONFIG_SEGMENTED_SDO             	1
#define EC_CONFIG_SLAVE                     	1
#define EC_CONFIG_STATE_TIMEOUT             	1
#define EC_CONFIG_STATE_TIMEOUT_BTOINIT     	8000
#define EC_CONFIG_STATE_TIMEOUT_BTOSAFE     	2000
#define EC_CONFIG_STATE_TIMEOUT_INITPREOP   	4000
#define EC_CONFIG_STATE_TIMEOUT_SAFEOP      	16000
#define EC_CONFIG_MAX_OD_ELEMENTS           	17
#define EC_CONFIG_MAX_RPDO_DATA             	97
#define EC_CONFIG_MAX_TPDO_DATA             	97



/*
 * Hardware configuration 0: 0
 */
 

/*
 * CPU Setup
 */
#ifdef EC_CONFIG_USE_TARGET_0
#define EC_CONFIG_CPU_FAMILY_GOAL           	1
#define EC_CONFIG_LIB_TIMER                 	1
#define EC_CONFIG_TIMER_INC                 	10
#include <goal_ethercat.h>
#endif /* EC_CONFIG_USE_TARGET_0*/


/*
 * Compiler Setup
 */
#ifdef EC_CONFIG_USE_TARGET_0
#define EC_CONFIG_COMPILER_GOAL             	1
#  include <ec_default.h>
#endif /* EC_CONFIG_USE_TARGET_0 */




/*
 * EtherCAT Services
 */

/* Sync Manager 0 */
#define EC_CONFIG_SM_0_COMM_TYPE 1
#define EC_CONFIG_SM_0_START_ADR 0x1000
#define EC_CONFIG_SM_0_DEFAULT_SIZE 246
#define EC_CONFIG_SM_0_MIN_SIZE 40
#define EC_CONFIG_SM_0_MAX_SIZE 1486
#define EC_CONFIG_SM_0_IRQ_ECAT_EVENT_ENABLED 0
#define EC_CONFIG_SM_0_IRQ_PDI_EVENT_ENABLED 1
#define EC_CONFIG_SM_0_WATCHDOG_ENABLED 0
#define EC_CONFIG_SM_0_ENABLED 1

/* Sync Manager 1 */
#define EC_CONFIG_SM_1_COMM_TYPE 2
#define EC_CONFIG_SM_1_START_ADR 0x1400
#define EC_CONFIG_SM_1_DEFAULT_SIZE 246
#define EC_CONFIG_SM_1_MIN_SIZE 40
#define EC_CONFIG_SM_1_MAX_SIZE 1486
#define EC_CONFIG_SM_1_IRQ_ECAT_EVENT_ENABLED 0
#define EC_CONFIG_SM_1_IRQ_PDI_EVENT_ENABLED 1
#define EC_CONFIG_SM_1_WATCHDOG_ENABLED 0
#define EC_CONFIG_SM_1_ENABLED 1

/* Sync Manager 2 */
#define EC_CONFIG_SM_2_COMM_TYPE 3
#define EC_CONFIG_SM_2_START_ADR 0x1800
#define EC_CONFIG_SM_2_DEFAULT_SIZE 97
#define EC_CONFIG_SM_2_IRQ_ECAT_EVENT_ENABLED 0
#define EC_CONFIG_SM_2_IRQ_PDI_EVENT_ENABLED 1
#define EC_CONFIG_SM_2_WATCHDOG_ENABLED 1
#define EC_CONFIG_SM_2_ENABLED 1

/* Sync Manager 3 */
#define EC_CONFIG_SM_3_COMM_TYPE 4
#define EC_CONFIG_SM_3_START_ADR 0x1C00
#define EC_CONFIG_SM_3_DEFAULT_SIZE 97
#define EC_CONFIG_SM_3_IRQ_ECAT_EVENT_ENABLED 0
#define EC_CONFIG_SM_3_IRQ_PDI_EVENT_ENABLED 1
#define EC_CONFIG_SM_3_WATCHDOG_ENABLED 0
#define EC_CONFIG_SM_3_ENABLED 1


/* Sync Manager general */
/* number of Sync Manager used for the standard receive mailbox */
#define EC_CONFIG_SM_STD_RX_MB 0
/* number of Sync Manager used for the standard send mailbox */
#define EC_CONFIG_SM_STD_TX_MB 1


#define EC_CONFIG_FLOAT_VALUES              	1
#define EC_CONFIG_MAPPING_CNT               	98
#define EC_CONFIG_PDO_CONSUMER              	1
#define EC_CONFIG_PDO_CONS_MAP_CNT          	49
#define EC_CONFIG_PDO_PRODUCER              	1
#define EC_CONFIG_PDO_PROD_MAP_CNT          	49
#define EC_CONFIG_SDO_SERVER                	1

/* 
 * special DEFINE part - don't edit here, it is changed by
 * the Industrial Communication Creator 
 */
#define EC_CONFIG_SPECIAL_START	1
/* access word-wise, use special mem-access */
#define EC_CONFIG_BSP 1



#define EC_CONFIG_SPECIAL_END	1

/* 
 * user specific part - will not be changed by
 * the Industrial Communication Creator
 */
#define EC_CONFIG_USER_SPEC_START	1

#define EC_CONFIG_USER_SPEC_END	1

#endif /* ECAT_CONF_H */
